name: linux-build

on:
  pull_request:
    branches:
    - master

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare
      run: sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5svg5-dev

    - name: make
      run: ./build.sh -DQT5_BUILD:BOOL="ON" -DQt5_PATH=$(dpkg -L qtbase5-dev) -DUSER_PYTHON_VERSION="3.5.6" -j3
