name: mac-build

on:
  pull_request:
    branches:
    - master

jobs:
  mac-build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare
      run: brew install qt

    - name: make
      run: ./build.sh -DUSER_PYTHON_VERSION="3.5.6" -DQT5_BUILD:BOOL="ON" -DQt5_PATH=$(brew --prefix qt) -j3
